name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  OPENAI_TOKEN: mockKey
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: checkout repo
        uses: actions/checkout@main
        
      - name: build code-generator
        run: make code-generator
        
      - name: build appwish-gui
        run: make appwish
      
    
  security:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@main
         working-directory:'cg/CodeGenerator/CodeGenerator/'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
          working-directory:'cg/CodeGenerator/CodeGenerator/'
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        

    

